name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.x'

    - name: Build
      run: go build

    - name: Test
      run: go test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    ##steps:
    ##- name: Deploy to Server
    ##  run: |
    ##    scp api-consumer user@your-server:/path/to/deploy
